# Generated by Django 3.2.4 on 2021-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0003_alter_imageupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='File',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
