# Generated by Django 3.2.4 on 2021-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0004_alter_imageupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
